# Generated by Django 5.0.4 on 2026-03-02 10:26

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FarmerQuery',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crop_type', models.CharField(max_length=100)),
                ('location', models.CharField(help_text='Latitude, longitude or place name', max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity in kg or quintals', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
            ],
            options={
                'db_table': 'farmer_queries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id', '-created_at'], name='farmer_quer_session_de6c7f_idx'), models.Index(fields=['status'], name='farmer_quer_status_cb6dfb_idx')],
            },
        ),
    ]
