# Generated by Django 5.0.4 on 2026-03-02 11:31

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CropRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('land_image', models.ImageField(blank=True, null=True, upload_to='land_images/')),
                ('location', models.CharField(help_text='Location for weather data', max_length=255)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('temperature', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('humidity', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('rainfall', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True)),
                ('soil_type', models.CharField(blank=True, max_length=100, null=True)),
                ('recommended_crops', models.JSONField(default=list)),
                ('analysis_data', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(max_length=255)),
                ('status', models.CharField(default='completed', max_length=20)),
            ],
            options={
                'db_table': 'crop_recommendations',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id', '-created_at'], name='crop_recomm_session_060a37_idx')],
            },
        ),
    ]
