# Generated by Django 5.0.4 on 2026-03-05 08:54

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_croprecommendation'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProfitAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crop_type', models.CharField(max_length=100)),
                ('land_area', models.DecimalField(decimal_places=2, help_text='Land area in acres', max_digits=10)),
                ('total_yield', models.DecimalField(decimal_places=2, help_text='Total yield in kg', max_digits=12)),
                ('seed_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fertilizer_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('labor_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('irrigation_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('other_costs', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('current_price', models.DecimalField(decimal_places=2, help_text='Current market price per kg', max_digits=10)),
                ('storage_capacity', models.CharField(max_length=100)),
                ('immediate_need', models.CharField(max_length=100)),
                ('processing_interest', models.CharField(max_length=100)),
                ('current_situation', models.JSONField(default=dict)),
                ('strategies', models.JSONField(default=list)),
                ('summary', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(max_length=255)),
                ('status', models.CharField(default='completed', max_length=20)),
            ],
            options={
                'db_table': 'profit_analyses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id', '-created_at'], name='profit_anal_session_01d71f_idx'), models.Index(fields=['crop_type'], name='profit_anal_crop_ty_b59e8e_idx')],
            },
        ),
    ]
