# Generated by Django 5.0.4 on 2026-03-05 09:33

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_profitanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='NegotiationAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crop_type', models.CharField(max_length=100)),
                ('farmer_location', models.CharField(max_length=255)),
                ('quantity', models.DecimalField(decimal_places=2, help_text='Quantity in quintals', max_digits=10)),
                ('offered_price', models.DecimalField(decimal_places=2, help_text='Price offered by buyer per quintal', max_digits=10)),
                ('nearby_market_prices', models.JSONField(default=list, help_text='List of nearby mandi prices')),
                ('offer_analysis', models.JSONField(default=dict)),
                ('fair_price_range', models.JSONField(default=dict)),
                ('negotiation_advice', models.JSONField(default=dict)),
                ('market_context', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session_id', models.CharField(max_length=255)),
                ('status', models.CharField(default='completed', max_length=20)),
            ],
            options={
                'db_table': 'negotiation_analyses',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['session_id', '-created_at'], name='negotiation_session_da29de_idx'), models.Index(fields=['crop_type'], name='negotiation_crop_ty_c7d4b7_idx')],
            },
        ),
    ]
