# Generated by Django 5.0.4 on 2026-03-05 10:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_negotiationanalysis'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChatMessage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('session_id', models.CharField(db_index=True, max_length=255)),
                ('user_message', models.TextField(help_text="User's question")),
                ('bot_response', models.TextField(help_text="AI assistant's response")),
                ('intent', models.CharField(help_text='Classified intent of the question', max_length=50)),
                ('entities', models.JSONField(default=dict, help_text='Extracted entities from question')),
                ('response_data', models.JSONField(default=dict, help_text='Additional response data')),
                ('suggestions', models.JSONField(default=list, help_text='Follow-up suggestions')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('response_time_ms', models.IntegerField(blank=True, help_text='Response time in milliseconds', null=True)),
            ],
            options={
                'db_table': 'chat_messages',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['session_id', 'created_at'], name='chat_messag_session_597c4e_idx'), models.Index(fields=['intent'], name='chat_messag_intent_1c44b7_idx')],
            },
        ),
    ]
