# Generated by Django 5.0.4 on 2026-03-02 10:16

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Market',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('location', models.CharField(help_text='Latitude, longitude', max_length=255)),
                ('mandi_code', models.CharField(max_length=50, unique=True)),
                ('region', models.CharField(max_length=100)),
                ('active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'markets',
                'indexes': [models.Index(fields=['mandi_code'], name='markets_mandi_c_163f70_idx'), models.Index(fields=['region'], name='markets_region_5d6528_idx')],
            },
        ),
        migrations.CreateModel(
            name='MarketPrice',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('crop_type', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('min_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('max_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('modal_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('arrivals', models.IntegerField(help_text='Quantity arrived at market')),
                ('source', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='market_data.market')),
            ],
            options={
                'db_table': 'market_prices',
                'ordering': ['-date'],
                'indexes': [models.Index(fields=['crop_type', '-date'], name='market_pric_crop_ty_642879_idx'), models.Index(fields=['market', 'crop_type'], name='market_pric_market__0c347a_idx')],
            },
        ),
        migrations.CreateModel(
            name='TransportCost',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_location', models.CharField(max_length=255)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cost_per_kg', models.DecimalField(decimal_places=2, max_digits=10)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('to_market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transport_costs', to='market_data.market')),
            ],
            options={
                'db_table': 'transport_costs',
                'unique_together': {('from_location', 'to_market')},
            },
        ),
    ]
