# Generated by Django 5.0.4 on 2026-03-02 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0001_initial'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='marketprice',
            constraint=models.CheckConstraint(check=models.Q(('min_price__lte', models.F('modal_price')), ('modal_price__lte', models.F('max_price'))), name='price_range_constraint'),
        ),
    ]
