# Generated by Django 5.0.4 on 2026-03-02 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market_data', '0002_marketprice_price_range_constraint'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='transportcost',
            constraint=models.CheckConstraint(check=models.Q(('distance_km__gte', 0)), name='distance_non_negative'),
        ),
        migrations.AddConstraint(
            model_name='transportcost',
            constraint=models.CheckConstraint(check=models.Q(('cost_per_kg__gte', 0)), name='cost_non_negative'),
        ),
    ]
