# Generated by Django 5.0.4 on 2026-03-02 10:27

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
        ('market_data', '0003_transportcost_distance_non_negative_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PriceAnalysis',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('fair_price_min', models.DecimalField(decimal_places=2, max_digits=10)),
                ('fair_price_max', models.DecimalField(decimal_places=2, max_digits=10)),
                ('confidence_score', models.FloatField(help_text='Confidence score between 0 and 1')),
                ('factors_considered', models.JSONField(default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='price_analysis', to='core.farmerquery')),
            ],
            options={
                'verbose_name_plural': 'Price analyses',
                'db_table': 'price_analyses',
            },
        ),
        migrations.CreateModel(
            name='MarketRecommendation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('expected_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('transport_cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('net_profit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('rank', models.IntegerField()),
                ('reasoning', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('market', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='market_data.market')),
                ('query', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recommendations', to='core.farmerquery')),
            ],
            options={
                'db_table': 'market_recommendations',
                'ordering': ['query', 'rank'],
                'indexes': [models.Index(fields=['query', 'rank'], name='market_reco_query_i_55d936_idx')],
            },
        ),
    ]
